### ISSUE TITLE
question regarding performance

### ISSUE THREAD

**Issue by mikekucera** [upsetjs/cytoscape.js-bubblesets#22]
In our app we are using bubblesets to outline clusters of nodes. We are running into performance issues with bubblesets when there are more than 500 edges in the cluster. The UI will freeze when rendering the bubble path.

Setting the throttle option to a higher value helps to prevent completely freezing the UI, but its still very unresponsive.

Creating a bubbleset with just the nodes and no edges does not create a desirable effect. If one node is dragged far away from the cluster then the bubbleset does not properly overlap the cluster edges anymore.

Ideally there would be an option to force the bubbleset to be convex, without having to create the bubbleset with edges. Is such a thing possible?

**Screenshots / Sketches**

What it looks like when created with edges, but this has performance issues...

<img width="612" alt="Screenshot 2023-11-01 at 3 45 36 PM" src="https://github.com/upsetjs/cytoscape.js-bubblesets/assets/5350528/31ebad6d-6feb-4ad0-9252-1ceab5724bba">

What it looks like when created without edges, much better performance but it doesn't look right...

<img width="617" alt="Screenshot 2023-11-01 at 3 45 09 PM" src="https://github.com/upsetjs/cytoscape.js-bubblesets/assets/5350528/fb38d175-9d94-4822-932e-f1d1bcd0ebae">

**Comment by sgratzl** [comment]
I don't think it is possible, the links are just other elements that should be covered by the bubblesets. So without them it will create the second picture. If you take a close look the two bubbles are still connected just with a way thinner connection. 

you could try to sample the edges instead of all edges like in the best case you just need the outer ones the ones in the middle won't add much.

**Comment by mikekucera** [comment]
Thanks for the response. We've taken the approach of sampling the edges and it works reasonably well.
