### ISSUE TITLE
Add Documentation for "IBubbleSetPathOptions"

### ISSUE THREAD

**Issue by simonwuelker** [upsetjs/cytoscape.js-bubblesets#5]
Having a list of possible options for `IBubbleSetPathOptions` would be nice. The [API Section](https://github.com/upsetjs/cytoscape.js-bubblesets#api) in `README.md` mentions this set of options but doesnt provide any further information.

**Comment by sgratzl** [comment]
see also https://github.com/upsetjs/cytoscape.js-bubblesets/blob/c2ebf0978a9c098a0cccfd7c85d4cef16c1721d2/src/BubbleSetPath.ts#L21-L30 and https://github.com/upsetjs/bubblesets-js/blob/c1285144fd16f189bc447a6d35402a2b3d3e7651/src/BubbleSets.ts#L12-L46

since I'm working mainly with an IDE that is supporting auto completion, I usually rely on it when coding and wonder regarding the possible options.

**Comment by simonwuelker** [comment]
Sorry but now im even more confused. Note that i dont know anything about typescript, i was just looking for a list of options to style my bubblesets. Based on these lines from one of your examples
https://github.com/upsetjs/cytoscape.js-bubblesets/blob/c2ebf0978a9c098a0cccfd7c85d4cef16c1721d2/samples/bubbleclusters.html#L48-L50
https://github.com/upsetjs/cytoscape.js-bubblesets/blob/c2ebf0978a9c098a0cccfd7c85d4cef16c1721d2/samples/bubbleclusters.html#L98 i assumed that it was basically just a javascript object with some attributes like `fillStyle` and maybe `borderStyle` etc. 
Im sorry if i didnt make that clear in my initial question (This is also why i initally posted this issue as an enhancement - I thought it would be nice to put a list of these options somewhere)

**Comment by simonwuelker** [comment]
When looking at this again, i noticed that what i was looking for was basically just this:
https://github.com/upsetjs/cytoscape.js-bubblesets/blob/c2ebf0978a9c098a0cccfd7c85d4cef16c1721d2/src/BubbleSetPath.ts#L32-L35

I just didnt know where to put my style attributes
